x-build-console: &build-console
  network_mode: "host"
  build:
    context: .
    target: cogip-console

x-build-gui: &build-gui
  network_mode: "host"
  build:
    context: .
    target: cogip-gui

x-build-firmware: &build-firmware
  network_mode: "host"
  build:
    context: .
    target: cogip-firmware

x-env-common: &env-common
  COGIP_SOCKETIO_SERVER_HOST: localhost
  COGIP_SOCKETIO_SERVER_PORT: 8090
  COGIP_SOCKETIO_SERVER_URL: http://localhost:8090

x-vol-cogip: &vol-cogip
  "./cogip:/src/cogip"

x-vol-run: &vol-run
  "run:/var/run/cogip"

x-vol-pts: &vol-pts
  "/dev/pts:/dev/pts"

x-vol-vscode: &vol-vscode
  "vscode:/root/.vscode-server"

x-volumes-common: &volumes-common
  volumes:
    - *vol-cogip
    - *vol-run
    - *vol-pts
    - *vol-vscode

x-extra-hosts-common: &extra-hosts-common
  extra_hosts:
    host.docker.internal: host-gateway

x-socketcan: &socketcan
  <<: *build-console
  privileged: true
  volumes:
    - *vol-run
    - *vol-pts
  command:
    - /bin/sh
    - -x
    - -c
    - |
      ip link add dev vcan0 type vcan bitrate 500000 dbitrate 1000000 fd on sample-point 0.875 mtu 72
      ip link set up vcan0
      sleep infinity

x-firmware: &firmware
  <<: *build-firmware
  environment: &env-firmware
    FIRMWARE_APP: ${FIRMWARE_APP:-cup2023}
    FIRMWARE_BOARD: ${FIRMWARE_BOARD:-cogip-native}
  stdin_open: true
  tty: true
  working_dir: /cogip/mcu-firmware
  volumes:
    - *vol-run
    - *vol-pts
    - *vol-vscode
    - "..:/cogip"
  command:
    - /bin/sh
    - -x
    - -c
    - |
      applications/$${FIRMWARE_APP}/bin/$${FIRMWARE_BOARD}/$${FIRMWARE_APP}.elf
      
      #make -C applications/$${FIRMWARE_APP} BOARD=$${FIRMWARE_BOARD} term
  depends_on: &depends-firmware
      make-firmware:
        condition: service_completed_successfully

x-robot: &robot
  <<: [*build-console, *volumes-common, *extra-hosts-common]
  hostname: robot1
  environment: &env-robot
    << : *env-common
    COPILOT_RELOAD:
    COPILOT_DEBUG:
    DETECTOR_RELOAD:
    DETECTOR_DEBUG:
    DETECTOR_UART_PORT:
    DETECTOR_UART_SPEED:
    DETECTOR_MIN_DISTANCE:
    DETECTOR_MAX_DISTANCE:
    DETECTOR_BEACON_RADIUS:
    DETECTOR_REFRESH_INTERVAL:
    DETECTOR_EMULATION: 1
  command:
    - /bin/sh
    - -x
    - -c
    - |
      wait-for-it -t 0 $${COGIP_SOCKETIO_SERVER_HOST}:$${COGIP_SOCKETIO_SERVER_PORT}
      cogip-copilot --can-channel vcan0 -b 500000 -B 1000000 &
      cogip-detector &
      sleep infinity
  depends_on:
    - beacon

services:
  beacon:
    <<: [*build-gui, *extra-hosts-common]
    hostname: beacon
    ports:
      - "8080:8080"
      - "8090:8090"
    environment:
      << : *env-common
      ROBOT_ID: 0
      SERVER_DEBUG:
      SERVER_RELOAD:
      PLANNER_DEBUG:
      PLANNER_RELOAD:
      PLANNER_ROBOT_WIDTH:
      PLANNER_OBSTACLE_RADIUS:
      PLANNER_OBSTACLE_BB_MARGIN:
      PLANNER_OBSTACLE_BB_VERTICES:
      PLANNER_OBSTACLE_SENDER_INTERVAL:
      PLANNER_PATH_REFRESH_INTERVAL:
    volumes:
      - *vol-cogip
      - *vol-vscode
      - "./records:/var/tmp/cogip"
    command:
      - /bin/sh
      - -x
      - -c
      - |
        cogip-server &
        cogip-dashboard &
        cogip-planner &
        sleep infinity

  monitor:
    << : [*build-gui, *extra-hosts-common]
    hostname: monitor
    environment:
      << : *env-common
      DISPLAY:
      QTWEBENGINE_DISABLE_SANDBOX: 1
      XDG_RUNTIME_DIR:
    command:
      - /bin/sh
      - -x
      - -c
      - |
        wait-for-it -t 0 $${COGIP_SOCKETIO_SERVER_HOST}:$${COGIP_SOCKETIO_SERVER_PORT}
        cogip-monitor &
        sleep infinity
    working_dir: /src
    depends_on:
      - beacon
    volumes:
      - *vol-cogip
      - *vol-vscode
      - "./assets:/src/assets"
      - "/tmp/.X11-unix/:/tmp/.X11-unix/"
      - "/dev/dri/:/dev/dri/"
      - "$XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR"
    profiles:
      - monitor

  socketcan1:
    << : *socketcan
    hostname: socketcan1
    environment:
      ROBOT_ID: 1
    profiles:
      - robot1

  socketcan2:
    << : *socketcan
    hostname: socketcan2
    environment:
      ROBOT_ID: 2
    profiles:
      - robot2

  make-firmware:
    <<: *build-firmware
    environment:
      << : *env-firmware
    working_dir: /cogip/mcu-firmware
    volumes:
      - "..:/cogip"
    command:
      - /bin/sh
      - -x
      - -c
      - |
        git config --global user.email "cogip35@gmail.com"
        git config --global user.name "COGIP Team"
        git config --global --add safe.directory /cogip/RIOT
        make -C applications/$${FIRMWARE_APP} -j$$(nproc) BOARD=$${FIRMWARE_BOARD}

  firmware1:
    << : *firmware
    hostname: firmware1
    environment:
      << : *env-firmware
      ROBOT_ID: 1
    depends_on:
      << : *depends-firmware
      socketcan1:
        condition: service_started
    profiles:
      - robot1

  firmware2:
    << : *firmware
    hostname: firmware2
    environment:
      << : *env-firmware
      ROBOT_ID: 2
    depends_on:
      << : *depends-firmware
      socketcan2:
        condition: service_started
    profiles:
      - robot2

  robot1:
    << : *robot
    hostname: robot1
    environment:
      << : *env-robot
      ROBOT_ID: 1
    depends_on:
      - socketcan1
      - beacon
    profiles:
      - robot1

  robot2:
    << : *robot
    hostname: robot2
    environment:
      << : *env-robot
      ROBOT_ID: 2
    depends_on:
      - socketcan2
      - beacon
    profiles:
      - robot2

volumes:
  vscode:
  run:
