# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_Pid.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PB_PidEnum_pb2 as PB__PidEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cPB_Pid.proto\x1a\x10PB_PidEnum.proto\"\x91\x01\n\x06PB_Pid\x12\x17\n\x02id\x18\x01 \x01(\x0e\x32\x0b.PB_PidEnum\x12\n\n\x02kp\x18\x02 \x01(\x01\x12\n\n\x02ki\x18\x03 \x01(\x01\x12\n\n\x02kd\x18\x04 \x01(\x01\x12\x16\n\x0eprevious_error\x18\x05 \x01(\x01\x12\x15\n\rintegral_term\x18\x06 \x01(\x01\x12\x1b\n\x13integral_term_limit\x18\x07 \x01(\x01\"$\n\tPB_Pid_Id\x12\x17\n\x02id\x18\x01 \x01(\x0e\x32\x0b.PB_PidEnumb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PB_Pid_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PB_PID._serialized_start=35
  _PB_PID._serialized_end=180
  _PB_PID_ID._serialized_start=182
  _PB_PID_ID._serialized_end=218
# @@protoc_insertion_point(module_scope)
