# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_Controller.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PB_Controller.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13PB_Controller.proto\"/\n\rPB_Controller\x12\x1e\n\x02id\x18\x01 \x01(\x0e\x32\x12.PB_ControllerEnum*i\n\x11PB_ControllerEnum\x12\x0b\n\x07QUADPID\x10\x00\x12\x16\n\x12\x41NGULAR_SPEED_TEST\x10\x01\x12\x15\n\x11LINEAR_SPEED_TEST\x10\x02\x12\x18\n\x14LINEAR_POSE_DISABLED\x10\x03\x62\x06proto3'
)

_PB_CONTROLLERENUM = _descriptor.EnumDescriptor(
  name='PB_ControllerEnum',
  full_name='PB_ControllerEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='QUADPID', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ANGULAR_SPEED_TEST', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LINEAR_SPEED_TEST', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LINEAR_POSE_DISABLED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=72,
  serialized_end=177,
)
_sym_db.RegisterEnumDescriptor(_PB_CONTROLLERENUM)

PB_ControllerEnum = enum_type_wrapper.EnumTypeWrapper(_PB_CONTROLLERENUM)
QUADPID = 0
ANGULAR_SPEED_TEST = 1
LINEAR_SPEED_TEST = 2
LINEAR_POSE_DISABLED = 3



_PB_CONTROLLER = _descriptor.Descriptor(
  name='PB_Controller',
  full_name='PB_Controller',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PB_Controller.id', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=70,
)

_PB_CONTROLLER.fields_by_name['id'].enum_type = _PB_CONTROLLERENUM
DESCRIPTOR.message_types_by_name['PB_Controller'] = _PB_CONTROLLER
DESCRIPTOR.enum_types_by_name['PB_ControllerEnum'] = _PB_CONTROLLERENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PB_Controller = _reflection.GeneratedProtocolMessageType('PB_Controller', (_message.Message,), {
  'DESCRIPTOR' : _PB_CONTROLLER,
  '__module__' : 'PB_Controller_pb2'
  # @@protoc_insertion_point(class_scope:PB_Controller)
  })
_sym_db.RegisterMessage(PB_Controller)


# @@protoc_insertion_point(module_scope)
