# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_GameOutputMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PB_Menu_pb2 as PB__Menu__pb2
import PB_State_pb2 as PB__State__pb2
import PB_Wizard_pb2 as PB__Wizard__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PB_GameOutputMessage.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1aPB_GameOutputMessage.proto\x1a\rPB_Menu.proto\x1a\x0ePB_State.proto\x1a\x0fPB_Wizard.proto\"\x83\x01\n\x14PB_GameOutputMessage\x12\x0f\n\x05reset\x18\x01 \x01(\x08H\x00\x12\x18\n\x04menu\x18\x02 \x01(\x0b\x32\x08.PB_MenuH\x00\x12\x1a\n\x05state\x18\x03 \x01(\x0b\x32\t.PB_StateH\x00\x12\x1c\n\x06wizard\x18\x04 \x01(\x0b\x32\n.PB_WizardH\x00\x42\x06\n\x04typeb\x06proto3')
  ,
  dependencies=[PB__Menu__pb2.DESCRIPTOR,PB__State__pb2.DESCRIPTOR,PB__Wizard__pb2.DESCRIPTOR,])




_PB_GAMEOUTPUTMESSAGE = _descriptor.Descriptor(
  name='PB_GameOutputMessage',
  full_name='PB_GameOutputMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reset', full_name='PB_GameOutputMessage.reset', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='menu', full_name='PB_GameOutputMessage.menu', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='PB_GameOutputMessage.state', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wizard', full_name='PB_GameOutputMessage.wizard', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='PB_GameOutputMessage.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=79,
  serialized_end=210,
)

_PB_GAMEOUTPUTMESSAGE.fields_by_name['menu'].message_type = PB__Menu__pb2._PB_MENU
_PB_GAMEOUTPUTMESSAGE.fields_by_name['state'].message_type = PB__State__pb2._PB_STATE
_PB_GAMEOUTPUTMESSAGE.fields_by_name['wizard'].message_type = PB__Wizard__pb2._PB_WIZARD
_PB_GAMEOUTPUTMESSAGE.oneofs_by_name['type'].fields.append(
  _PB_GAMEOUTPUTMESSAGE.fields_by_name['reset'])
_PB_GAMEOUTPUTMESSAGE.fields_by_name['reset'].containing_oneof = _PB_GAMEOUTPUTMESSAGE.oneofs_by_name['type']
_PB_GAMEOUTPUTMESSAGE.oneofs_by_name['type'].fields.append(
  _PB_GAMEOUTPUTMESSAGE.fields_by_name['menu'])
_PB_GAMEOUTPUTMESSAGE.fields_by_name['menu'].containing_oneof = _PB_GAMEOUTPUTMESSAGE.oneofs_by_name['type']
_PB_GAMEOUTPUTMESSAGE.oneofs_by_name['type'].fields.append(
  _PB_GAMEOUTPUTMESSAGE.fields_by_name['state'])
_PB_GAMEOUTPUTMESSAGE.fields_by_name['state'].containing_oneof = _PB_GAMEOUTPUTMESSAGE.oneofs_by_name['type']
_PB_GAMEOUTPUTMESSAGE.oneofs_by_name['type'].fields.append(
  _PB_GAMEOUTPUTMESSAGE.fields_by_name['wizard'])
_PB_GAMEOUTPUTMESSAGE.fields_by_name['wizard'].containing_oneof = _PB_GAMEOUTPUTMESSAGE.oneofs_by_name['type']
DESCRIPTOR.message_types_by_name['PB_GameOutputMessage'] = _PB_GAMEOUTPUTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PB_GameOutputMessage = _reflection.GeneratedProtocolMessageType('PB_GameOutputMessage', (_message.Message,), dict(
  DESCRIPTOR = _PB_GAMEOUTPUTMESSAGE,
  __module__ = 'PB_GameOutputMessage_pb2'
  # @@protoc_insertion_point(class_scope:PB_GameOutputMessage)
  ))
_sym_db.RegisterMessage(PB_GameOutputMessage)


# @@protoc_insertion_point(module_scope)
