# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_Menu.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PB_Command_pb2 as PB__Command__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rPB_Menu.proto\x1a\x10PB_Command.proto\"5\n\x07PB_Menu\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1c\n\x07\x65ntries\x18\x03 \x03(\x0b\x32\x0b.PB_Commandb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PB_Menu_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PB_MENU._serialized_start=35
  _PB_MENU._serialized_end=88
# @@protoc_insertion_point(module_scope)
