# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_Obstacle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PB_Coords_pb2 as PB__Coords__pb2
import PB_Rectangle_pb2 as PB__Rectangle__pb2
import PB_Circle_pb2 as PB__Circle__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PB_Obstacle.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11PB_Obstacle.proto\x1a\x0fPB_Coords.proto\x1a\x12PB_Rectangle.proto\x1a\x0fPB_Circle.proto\"}\n\x0bPB_Obstacle\x12\"\n\trectangle\x18\x01 \x01(\x0b\x32\r.PB_RectangleH\x00\x12\x1c\n\x06\x63ircle\x18\x02 \x01(\x0b\x32\n.PB_CircleH\x00\x12 \n\x0c\x62ounding_box\x18\x03 \x03(\x0b\x32\n.PB_CoordsB\n\n\x08obstacleb\x06proto3')
  ,
  dependencies=[PB__Coords__pb2.DESCRIPTOR,PB__Rectangle__pb2.DESCRIPTOR,PB__Circle__pb2.DESCRIPTOR,])




_PB_OBSTACLE = _descriptor.Descriptor(
  name='PB_Obstacle',
  full_name='PB_Obstacle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rectangle', full_name='PB_Obstacle.rectangle', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='circle', full_name='PB_Obstacle.circle', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bounding_box', full_name='PB_Obstacle.bounding_box', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='obstacle', full_name='PB_Obstacle.obstacle',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=75,
  serialized_end=200,
)

_PB_OBSTACLE.fields_by_name['rectangle'].message_type = PB__Rectangle__pb2._PB_RECTANGLE
_PB_OBSTACLE.fields_by_name['circle'].message_type = PB__Circle__pb2._PB_CIRCLE
_PB_OBSTACLE.fields_by_name['bounding_box'].message_type = PB__Coords__pb2._PB_COORDS
_PB_OBSTACLE.oneofs_by_name['obstacle'].fields.append(
  _PB_OBSTACLE.fields_by_name['rectangle'])
_PB_OBSTACLE.fields_by_name['rectangle'].containing_oneof = _PB_OBSTACLE.oneofs_by_name['obstacle']
_PB_OBSTACLE.oneofs_by_name['obstacle'].fields.append(
  _PB_OBSTACLE.fields_by_name['circle'])
_PB_OBSTACLE.fields_by_name['circle'].containing_oneof = _PB_OBSTACLE.oneofs_by_name['obstacle']
DESCRIPTOR.message_types_by_name['PB_Obstacle'] = _PB_OBSTACLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PB_Obstacle = _reflection.GeneratedProtocolMessageType('PB_Obstacle', (_message.Message,), dict(
  DESCRIPTOR = _PB_OBSTACLE,
  __module__ = 'PB_Obstacle_pb2'
  # @@protoc_insertion_point(class_scope:PB_Obstacle)
  ))
_sym_db.RegisterMessage(PB_Obstacle)


# @@protoc_insertion_point(module_scope)
