# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_Obstacles.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PB_Rectangle_pb2 as PB__Rectangle__pb2
import PB_Circle_pb2 as PB__Circle__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PB_Obstacles.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12PB_Obstacles.proto\x1a\x12PB_Rectangle.proto\x1a\x0fPB_Circle.proto\"N\n\x0cPB_Obstacles\x12\x1b\n\x07\x63ircles\x18\x01 \x03(\x0b\x32\n.PB_Circle\x12!\n\nrectangles\x18\x02 \x03(\x0b\x32\r.PB_Rectangleb\x06proto3')
  ,
  dependencies=[PB__Rectangle__pb2.DESCRIPTOR,PB__Circle__pb2.DESCRIPTOR,])




_PB_OBSTACLES = _descriptor.Descriptor(
  name='PB_Obstacles',
  full_name='PB_Obstacles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='circles', full_name='PB_Obstacles.circles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rectangles', full_name='PB_Obstacles.rectangles', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=137,
)

_PB_OBSTACLES.fields_by_name['circles'].message_type = PB__Circle__pb2._PB_CIRCLE
_PB_OBSTACLES.fields_by_name['rectangles'].message_type = PB__Rectangle__pb2._PB_RECTANGLE
DESCRIPTOR.message_types_by_name['PB_Obstacles'] = _PB_OBSTACLES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PB_Obstacles = _reflection.GeneratedProtocolMessageType('PB_Obstacles', (_message.Message,), dict(
  DESCRIPTOR = _PB_OBSTACLES,
  __module__ = 'PB_Obstacles_pb2'
  # @@protoc_insertion_point(class_scope:PB_Obstacles)
  ))
_sym_db.RegisterMessage(PB_Obstacles)


# @@protoc_insertion_point(module_scope)
