# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_PidEnum.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10PB_PidEnum.proto*d\n\nPB_PidEnum\x12\x13\n\x0fLINEAR_POSE_PID\x10\x00\x12\x14\n\x10\x41NGULAR_POSE_PID\x10\x01\x12\x14\n\x10LINEAR_SPEED_PID\x10\x02\x12\x15\n\x11\x41NGULAR_SPEED_PID\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PB_PidEnum_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PB_PIDENUM._serialized_start=20
  _PB_PIDENUM._serialized_end=120
# @@protoc_insertion_point(module_scope)
