# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_PathPose.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PB_SpeedEnum_pb2 as PB__SpeedEnum__pb2
import PB_Pose_pb2 as PB__Pose__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PB_PathPose.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11PB_PathPose.proto\x1a\x12PB_SpeedEnum.proto\x1a\rPB_Pose.proto\"\x99\x01\n\x0bPB_PathPose\x12\x16\n\x04pose\x18\x01 \x01(\x0b\x32\x08.PB_Pose\x12,\n\x15max_speed_linear_enum\x18\x02 \x01(\x0e\x32\r.PB_SpeedEnum\x12-\n\x16max_speed_angular_enum\x18\x03 \x01(\x0e\x32\r.PB_SpeedEnum\x12\x15\n\rallow_reverse\x18\x04 \x01(\x08\x62\x06proto3')
  ,
  dependencies=[PB__SpeedEnum__pb2.DESCRIPTOR,PB__Pose__pb2.DESCRIPTOR,])




_PB_PATHPOSE = _descriptor.Descriptor(
  name='PB_PathPose',
  full_name='PB_PathPose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pose', full_name='PB_PathPose.pose', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_speed_linear_enum', full_name='PB_PathPose.max_speed_linear_enum', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_speed_angular_enum', full_name='PB_PathPose.max_speed_angular_enum', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='allow_reverse', full_name='PB_PathPose.allow_reverse', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=210,
)

_PB_PATHPOSE.fields_by_name['pose'].message_type = PB__Pose__pb2._PB_POSE
_PB_PATHPOSE.fields_by_name['max_speed_linear_enum'].enum_type = PB__SpeedEnum__pb2._PB_SPEEDENUM
_PB_PATHPOSE.fields_by_name['max_speed_angular_enum'].enum_type = PB__SpeedEnum__pb2._PB_SPEEDENUM
DESCRIPTOR.message_types_by_name['PB_PathPose'] = _PB_PATHPOSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PB_PathPose = _reflection.GeneratedProtocolMessageType('PB_PathPose', (_message.Message,), dict(
  DESCRIPTOR = _PB_PATHPOSE,
  __module__ = 'PB_PathPose_pb2'
  # @@protoc_insertion_point(class_scope:PB_PathPose)
  ))
_sym_db.RegisterMessage(PB_PathPose)


# @@protoc_insertion_point(module_scope)
