# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_Pose.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PB_Pose.proto',
  package='cogip.cogip_defs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rPB_Pose.proto\x12\x10\x63ogip.cogip_defs\"*\n\x07PB_Pose\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01O\x18\x03 \x01(\x01\x62\x06proto3')
)




_PB_POSE = _descriptor.Descriptor(
  name='PB_Pose',
  full_name='cogip.cogip_defs.PB_Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='cogip.cogip_defs.PB_Pose.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='cogip.cogip_defs.PB_Pose.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='O', full_name='cogip.cogip_defs.PB_Pose.O', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['PB_Pose'] = _PB_POSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PB_Pose = _reflection.GeneratedProtocolMessageType('PB_Pose', (_message.Message,), dict(
  DESCRIPTOR = _PB_POSE,
  __module__ = 'PB_Pose_pb2'
  # @@protoc_insertion_point(class_scope:cogip.cogip_defs.PB_Pose)
  ))
_sym_db.RegisterMessage(PB_Pose)


# @@protoc_insertion_point(module_scope)
