# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_Score.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PB_Score.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0ePB_Score.proto\"\x19\n\x08PB_Score\x12\r\n\x05value\x18\x01 \x01(\x05\x62\x06proto3')
)




_PB_SCORE = _descriptor.Descriptor(
  name='PB_Score',
  full_name='PB_Score',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='PB_Score.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=43,
)

DESCRIPTOR.message_types_by_name['PB_Score'] = _PB_SCORE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PB_Score = _reflection.GeneratedProtocolMessageType('PB_Score', (_message.Message,), dict(
  DESCRIPTOR = _PB_SCORE,
  __module__ = 'PB_Score_pb2'
  # @@protoc_insertion_point(class_scope:PB_Score)
  ))
_sym_db.RegisterMessage(PB_Score)


# @@protoc_insertion_point(module_scope)
