# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_State.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PB_Polar_pb2 as PB__Polar__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ePB_State.proto\x1a\x0ePB_Polar.proto\"[\n\x08PB_State\x12\r\n\x05\x63ycle\x18\x02 \x01(\r\x12 \n\rspeed_current\x18\x03 \x01(\x0b\x32\t.PB_Polar\x12\x1e\n\x0bspeed_order\x18\x04 \x01(\x0b\x32\t.PB_Polarb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PB_State_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PB_STATE._serialized_start=34
  _PB_STATE._serialized_end=125
# @@protoc_insertion_point(module_scope)
